import { PostDto } from "../app/components/post-list";

export const posts: PostDto[] = [
    {
      id: 'x-1',
      title: 'Mdx examples',
      description: 'Example to demonstrate mdx format',
      url: 'mdx/example.mdx',
      tags: ['markdown'],
      authors: ['Deepak Kumar'],
    },
    {
      id: 'x-2',
      title: 'Binary Heap',
      description: 'A discussion about binary heap data structure',
      url: 'mdx/binary-heap.mdx',
      tags: ['data-structures', 'binary-heap', 'javascript', 'typescript'],
      authors: ['Deepak Kumar'],
    },
    {
        id: 'x-3',
        title: 'Binary Heap',
        description: 'A discussion about binary heap data structure',
        url: 'mdx/binary-heap.mdx',
        tags: ['data-structures', 'binary-heap', 'javascript', 'typescript'],
        authors: ['Deepak Kumar'],
      },
      {
        id: 'x-4',
        title: 'Binary Heap',
        description: 'A discussion about binary heap data structure',
        url: 'mdx/binary-heap.mdx',
        tags: ['data-structures', 'binary-heap', 'javascript', 'typescript'],
        authors: ['Deepak Kumar'],
      },
      {
        id: 'x-5',
        title: 'Binary Heap',
        description: 'A discussion about binary heap data structure',
        url: 'mdx/binary-heap.mdx',
        tags: ['data-structures', 'binary-heap', 'javascript', 'typescript'],
        authors: ['Deepak Kumar'],
      },
      {
        id: 'x-6',
        title: 'Binary Heap',
        description: 'A discussion about binary heap data structure',
        url: 'mdx/binary-heap.mdx',
        tags: ['data-structures', 'binary-heap', 'javascript', 'typescript'],
        authors: ['Deepak Kumar'],
      },
      {
        id: 'x-7',
        title: 'Binary Heap',
        description: 'A discussion about binary heap data structure',
        url: 'mdx/binary-heap.mdx',
        tags: ['data-structures', 'binary-heap', 'javascript', 'typescript'],
        authors: ['Deepak Kumar'],
      },
      {
        id: 'x-8',
        title: 'Binary Heap',
        description: 'A discussion about binary heap data structure',
        url: 'mdx/binary-heap.mdx',
        tags: ['data-structures', 'binary-heap', 'javascript', 'typescript'],
        authors: ['Deepak Kumar'],
      },
      {
        id: 'x-9',
        title: 'Binary Heap',
        description: 'A discussion about binary heap data structure',
        url: 'mdx/binary-heap.mdx',
        tags: ['data-structures', 'binary-heap', 'javascript', 'typescript'],
        authors: ['Deepak Kumar'],
      },
  ];